name: CustomArrows
main: io.github.gustav9797.CustomArrows.CustomArrows
version: 0.1
commands:
   buyarrows:
      description: Buys custom arrows.
      usage: /buyarrows <type> <amount>
      permission: customarrows.buyarrows
      permission-message: You don't have customarrows.buyarrows