name: CustomArrows
main: io.github.gustav9797.CustomArrows.CustomArrows
version: 0.1
commands:
   poisonarrows:
      description: Gives you a stack of poison arrows.
      usage: /poisonarrows
      permission: customarrows.poison
      permission-message: You don't have customarrows.poison